apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
  labels:
    app: logstash
data:
  wojny-laserowe.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [fields][service] == "wojny-laserowe" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}" }
        }
        
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        
        mutate {
          add_field => { "service" => "wojny-laserowe" }
          add_field => { "environment" => "%{[fields][environment]}" }
        }
      }
      
      if [fields][service] == "nginx" {
        grok {
          match => { "message" => "%{NGINXACCESS}" }
        }
        
        mutate {
          add_field => { "service" => "nginx" }
        }
      }
      
      if [fields][service] == "postgresql" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}" }
        }
        
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        
        mutate {
          add_field => { "service" => "postgresql" }
        }
      }
      
      if [fields][service] == "redis" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}" }
        }
        
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        
        mutate {
          add_field => { "service" => "redis" }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-settings
  namespace: monitoring
  labels:
    app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
    xpack.security.enabled: false
