// Generic UI components - reusable across features
export { default as CardWithIcon } from './CardWithIcon';
export { default as CopyRow } from './CopyRow';
export { default as CTASection } from './CTASection';
export { default as InstagramSection } from './InstagramSection';
export { default as LoadingSpinner } from './LoadingSpinner';
export { default as LocationSection } from './LocationSection';
export { default as MapSection } from './MapSection';
export { default as OfferSlider } from './OfferSlider';
export { default as PageHeader } from './PageHeader';
export { default as ProcessSectionDefault } from './ProcessSectionDefault';
export { default as RemovalHero } from './RemovalHero';
export { default as ScarinkHero } from './ScarinkHero';
// ScarinkWhyChooseSection deprecated - use WhyChooseSection with variant='scarink' instead
export { default as SocialMediaIcons } from './SocialMediaIcons';
export { default as StagesSection } from './StagesSection';
export { default as StatusMessage } from './StatusMessage';
export { default as TestimonialsCarousel } from './TestimonialsCarousel';
export { default as TestimonialsPlaceholder } from './TestimonialsPlaceholder';
export { default as WhyChooseSection } from './WhyChooseSection';
