apiVersion: v1
kind: ConfigMap
metadata:
  name: wojny-laserowe-config
  namespace: wojny-laserowe-dev
  labels:
    app: wojny-laserowe
    component: config
data:
  # Application Configuration
  NODE_ENV: "development"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  
  # Feature Flags
  FEATURE_NEW_GALLERY: "true"
  FEATURE_DARK_MODE: "false"
  FEATURE_NOTIFICATIONS: "true"
  FEATURE_OFFLINE_MODE: "false"
  
  # Upload Configuration
  UPLOAD_MAX_SIZE: "10485760"
  UPLOAD_ALLOWED_TYPES: "image/jpeg,image/png,image/webp"
  
  # Monitoring
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3001"
  
  # Next.js Configuration
  NEXT_TELEMETRY_DISABLED: "1"
  
  # Logging
  LOG_LEVEL: "debug"
  
  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "100"
