apiVersion: apps/v1
kind: Deployment
metadata:
  name: wojny-laserowe-app
  namespace: wojny-laserowe-dev
  labels:
    app: wojny-laserowe
    component: app
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wojny-laserowe
      component: app
  template:
    metadata:
      labels:
        app: wojny-laserowe
        component: app
        version: v1.0.0
    spec:
      containers:
      - name: app
        image: wojny-laserowe:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: wojny-laserowe-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: wojny-laserowe-config
              key: PORT
        - name: HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: wojny-laserowe-config
              key: HOSTNAME
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: wojny-laserowe-secrets
              key: NEXTAUTH_SECRET
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: wojny-laserowe-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wojny-laserowe-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: wojny-laserowe-secrets
              key: POSTGRES_DB
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
