name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          NODE_ENV: production
          # Minimal env to placate validation if referenced
          NEXTAUTH_SECRET: dummy-secret-please-set-in-vercel-0123456789abcdef0123456789abcd
        run: npm run build

      - name: Start app
        env:
          NODE_ENV: production
          PORT: 3000
        run: |
          nohup npm start >/dev/null 2>&1 &
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/ > /dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done; exit 1

      - name: Smoke test - homepage
        run: |
          curl -fsS http://localhost:3000/ | head -n 20

      - name: Smoke test - health
        run: |
          curl -fsS http://localhost:3000/api/health | jq '.' || curl -fsS http://localhost:3000/api/health
